POST http://localhost:8080/auth
Content-Type: application/json
#Authorization: Bearer eyJhbGciOiJIUzUxMiIsInppcCI6IkRFRiJ9.eNo0jM0KwjAQhN9lz13oxjRN-gaeevDSa362EBEVsy1C8d1NEG8z883MAVfJMAFr5bwOHskToVZhQLuOPQZif0pxVZosdFC2UMtUVS6lqr3ER2J8cZF4y3yXRrzARMPojCNjXAf8frbA9soZ3YLEe458TvVA6hJ_HnOCP5vb-XxZ4PMFAAD__w.1Knb6U4QymUsvC7ptFc31dKoKn6h-bYePtkyOuND_D7gTyWSpV_pRdvN1eLpS77opTNxa9iANSqsZXOr36J5qg

{
  "deviceId": "test-device-id",
  "deviceOS": "OSX",
  "password": "htoonlin",
  "user": "+959254378203"
}