package com.sdm.payment.model.request.kpay;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class KPayRequest implements Serializable {
    private static final long serialVersionUID = -2426992327806665614L;

    @JsonProperty("timestamp")
    private String timestamp;

    /*
    Merchant Callback Url
     */
    @JsonProperty("notify_url")
    private String notifyUrl;

    /*
    method	String	Yes	kbz.payment.precreate		Interface name: kbz.payment.precreate
     */
    @JsonProperty("method")
    private String method;

    /*
    Random character string containing a maximum of 32 characters, including uppercase letters, lowercase letters, digits, but not special characters
     */
    @JsonProperty("nonce_str")
    private String nonceStr;

    /*
    Signature type. Currently, only the value SHA256 is supported.
     */
    @JsonProperty("sign_type")
    private String signType;

    /*
    Service parameter set signature, which is case insensitive. (For details about the signature algorithm, see Signature Description.)
     */
    @JsonProperty("sign")
    private String sign;

    /*
        1.0	Interface version number.
     */
    @JsonProperty("version")
    private String version;

    /*
    Service parameter set. For detail, see below table.
     */
    @JsonProperty("biz_content")
    private String bizContent;

    @JsonProperty("appid")
    private String appId;

    /*
    Specifies an Official Account Code assigned by KBZPay
     */
    @JsonProperty("merch_code")
    private String merchCode;

    /*
    The order number generated by the merchant side. It must be in the form of letters, numbers, and underscores. Other special characters are not allowed.
     */
    @JsonProperty("merch_order_id")
    private String merchOrderId;

    /*
    APP Trade type. The option are APP
     */
    @JsonProperty("trade_type")
    private String tradeType;

    /*
    Offering name.
     */
    @JsonProperty("title")
    private String title;

    @JsonProperty("total_amount")
    private String totalAmount;

    /*
    Three-letter code complying with international standards, for example, MMK (Kyat).
     */
    @JsonProperty("trans_currency")
    private String transCurrency;

    /*
    Latest payment time allowed for an order. The transaction will be closed after the deadline. The value ranges from 1 minute to 120 minutes. The value of this parameter cannot contain dots. For example, the value 1.5 hours must be converted to 90 minutes. If this parameter is not set, 120 minutes is used by default.
     */
    @JsonProperty("timeout_express")
    private String timeoutExpress;

    /*
    After the payment is successful, KBZPay will notify the merchant server of the callback request to return this field as it is, and the
    merchant can pass the business parameters according to its own needs. Must be in URL encoding format.
     */
    @JsonProperty("callback_info")
    private String callbackInfo;

    /*
    Specifies a store operator ID (such as staff number as defined by the merchant)
     */
    @JsonProperty("operator_id")
    private String operatorId;

    /*
    Specifies a Store ID (such as store number as defined by the merchant)
     */
    @JsonProperty("store_id")
    private String storeId;

    /*
    Specifies a Terminal device ID
     */
    @JsonProperty("terminal_id")
    private String terminalId;

    /*
    Allow merchants to pass in additional business information, the specific value should be agreed with KBZPay, and applied to security, marketing and other parameters direct transmission scenarios. Must be URL encoded format
     */
    @JsonProperty("business_param")
    private String businessParam;
}
